# Create an EC2 Instance with a security group
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-02e136e904f3da870
      InstanceType: t2.micro
      KeyName: Key-demo-01
      SecurityGroups:
        - !Ref CloudFormedSG
      Tags: 
        - Key: Name
          Value: cloudformed
                  
  # Security group named CloudFormedSG
  CloudFormedSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP
      SecurityGroupIngress: 
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
